version: "3.9"
networks:
  step-master-dev:
      driver: bridge
services:
  app: 
    container_name: step-master
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5500:80"
    networks:
      - step-master-dev
    depends_on:
      - mongodb
  mongodb:
    container_name: step-master-mongo
    image: mongo:latest
    environment: # set required env variables to access mongo
       MONGO_INITDB_ROOT_USERNAME: root
       MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    networks:
      - step-master-dev
    volumes: # optional to preserve database after container is deleted.
      - /dataMongo:/data/db
